Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.box_url = "/Users/phil/.vagrant/boxes/lucid32/"
 
  config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = "cookbooks"
     chef.add_recipe "application::default"
     chef.add_recipe "application::python"
     chef.add_recipe "application::biotech"

     chef.json.merge!({ :pip_python_packages => {
          :virtualenv => "1.5.1",
          :mercurial => "1.7"
        },
        :ubuntu_python_packages => ["python-setuptools", "python-pip", "python-dev"],
        :base_packages => ["git-core", "bash-completion"],
        :virtual_env_path => "/home/vagrant/.virtualenvs"
      })
  end
end


# config.vm.boot_mode = :gui

  # Assign this VM to a host only network IP, allowing you to access it
  # via the IP.
  # config.vm.network "33.33.33.10"

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  # config.vm.forward_port "http", 80, 8080

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"

  # Enable provisioning with chef solo, specifying a cookbooks path (relative
  # to this Vagrantfile), and adding some recipes and/or roles.
  #